<?php

return [
    'verify_token' => 'fid.vn',
    'token' => 'EAAIPsfXgLCwBAPVvJi1krVQZAN2sI8vrVE83PW9fyqNPehyggF3z1jtKZB70dEEK2BZCxRHHPiJ7ZBpvmH0emMgACaWPjbZBTSQJx52J4hxg6y4vrKmjtyZCNk50quCblZAXMcGhUJDTJLEQi0ZBgiFyWq6bZBIMZA0VWJGOUBlcCVgwZDZD',
    'token_feed' => 'EAADo1TDZCuu8BANKNTPGfiZBQYnDE5ec2UzwiWUoWTuJ56xWyccbCAXjAt3a4ZAHNthAZAeX8RBgRGf5xSLMQWtNLxpe01dmXcEjb4C3WcbbXaZCKFZBRbhOaCwAaNZBn6UpYcmuZAIroxLkgu30xFKbj1KCDJuOFQ10eWor0ypqCgZDZD'
];